### PR TITLE
chore(deps): bump validator to 13.5.1

### PR DESCRIPTION
**Pull request by fedeci**
## Description

Update `validator` to 13.5.0
This allows to implement new validators and to add support to more locales.

## To-do list

- [x] I have added tests for what I changed.

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by ADumaine** [comment]
Would be nice to get `isBase58` included.

**Comment by fedeci** [comment]
Sure, I will add all the new validators

**Review by gustavohenke — CHANGES_REQUESTED** [review]
Thanks!
This is just one step though, typescript support needs to be updated.
Look for instance at #874 to see some of the places that need to be changed.

**Comment by fedeci** [comment]
I am working on that!😉

**Comment by fedeci** [comment]
@gustavohenke there should be everything

**Review by gustavohenke — APPROVED** [review]
Looking great, thank you very much!

**Comment by gustavohenke** [comment]
Shipped in v6.8.0!

**Pull request merged**
