### PR TITLE
fix(security): Bump lodash version to 4.17.21

### LINKED ISSUE #1003: High and medium severity issues found in lodash 4.17.20
Snyk is reporting 2 issues with lodash 4.17.20:
https://snyk.devtools.intel.com/vuln/SNYK-JS-LODASH-1040724
https://snyk.devtools.intel.com/vuln/SNYK-JS-LODASH-1018905

These issues are fixed in 4.17.21.  Do you want me to submit a pull request upping the lodash version?

### PR DESCRIPTION
**Pull request by matt-primrose**
## Description
Fixes #1003 
Bump lodash version from 4.17.20 to 4.17.21

## To-do list

- [x] I have added tests for what I changed.

- [x] This pull request is ready to merge.

### CODE REVIEW

**Review by fedeci — CHANGES_REQUESTED** [review]
We should update also `package-lock.json`.

**Comment by matt-primrose** [comment]
package-lock.json has been updated to lodash version 4.17.21 as well

**Review by fedeci — APPROVED** [review]
Thanks!

**Comment by JCass45** [comment]
Hey, when will this patch be released?

**Comment by gustavohenke** [comment]
Done @JCass45, published as v6.10.1! Sorry for the delay.

**Comment by JCass45** [comment]
@gustavohenke Thanks man! 🙏🏻

**Pull request merged**
