### PR TITLE
Conditional validation

### LINKED ISSUE #439: Conditional Validation
Hello, technocrats!

I'm facing a hard time implementing conditional validation. As per the new API version, validation checks are passed in the form of an array as a second parameter, well, this is what I could infer, to the routing methods. Lemme give you a scenario to make it clear. 

I have a login page with two tabs defining Student Login and Teacher Login. Each tab has a Bootstrap Form with Student ID (or Teacher ID) input field, a Password input field, a hidden input with a fixed value for each (say SID for student and TID for teacher),  and a submit button. The POST method for the page is defined in index.js. 
Now, the issue is I need to check the value of the hidden input first and on the basis of that only I need to choose the right route for the student and the teacher. I need to check all the input validations also for respective fields in Student Login form and Teacher Login form. It's just like dealing with two forms in one POST method. Where should I be writing the conditional code for the route?

Any help is heartily appreciated.

Thank you
Arvind Jaiswal

### PR DESCRIPTION
**Pull request by gustavohenke**
Closes #439.

<details>
<summary>OLD suggested API</summary>
API looks like this at the moment:

```js
checkIf(check('id').exists(), check('password').isSomething())
```

- [x] Runs validation chains as conditions
- [x] Runs `oneOf()` as condition
- [x] Runs any middleware as validations
- [x] Docs
</details>

NEW suggested API looks like this:

```js
body('oldPassword')
  // if the new password is provided...
  .if((value, { req }) => req.body.newPassword)
  // OR
  .if(body('newPassword').exists())
  // ...then the old password must be too...
  .not().empty()
  // ...and they must not be equal.
  .custom((value, { req }) => value !== req.body.newPassword)
```

### CODE REVIEW

**Comment by nickcolley** [comment]
This is a really useful feature, thanks @gustavohenke for contributing. Hope this gets merged soon so we can remove our custom validators :)

**Comment by hicaro** [comment]
Very neat! Thanks for working on this @gustavohenke! Awesome job 🥇. 

Does anybody know when it will be merged?

**Comment by AyushG3112** [comment]
Any estimate on a merge and a release soon please?

**Comment by abhisekp** [comment]
Can this solve the issue where I've a single schema to check for both an object in the body and an array of objects in the body by using wildcards?

e.g.
I've a schema for a single object and I extend it to check for array of objects using the following function. I'm checking it using `oneOf([checkSchema(schema), checkSchema(arraySchema)]);`. But the tragedy is it sometimes, does not work. So it could be great, if the body is checked for if array, then run the `arraySchema`. Otherwise, run the normal `schema`.

```js
/* eslint-disable no-param-reassign */
import _ from 'lodash';

export const convertToArraySchema = schema => _.transform(
  schema,
  (result, value, key) => {
    if (/\bbody\b/.test(`${value.in}`)) {
      result[`*.${key}`] = value;
    } else {
      result[key] = value;
    }
  },
  {},
);

export default convertToArraySchema;

```

**Comment by AyushG3112** [comment]
pinging again

**Comment by Hum4n01d** [comment]
Please merge this :smile:

**Comment by gustavohenke** [comment]
Hello all.
This has been refactored now that version 6 is out.

The new proposal looks like this:

```js
body('oldPassword')
  // if the new password is provided...
  .if((value, { req }) => req.body.newPassword)
  // ...then the old password must be too...
  .not().empty()
  // ...and they must not be equal.
  .custom((value, { req }) => value !== req.body.newPassword)
```

This might not be as powerful as the old one _for now_, as all you can do is pass a custom validator-like function.
It is however nicer, and closer to what I'd like for express-validator's future.

**Comment by Hum4n01d** [comment]
Glad to see there’s been work on this, I ended up using the validator library directly and writing the logic with if statements manually for each request. Are there any reasons to use this library instead?

**Comment by gustavohenke** [comment]
> I ended up using the validator library directly and writing the logic with if statements manually for each request. Are there any reasons to use this library instead?

Hi @Hum4n01d!
express-validator provides a nice declarative API to abstract validation and sanitisation logic away from your route handlers. It makes it easier to standardise the way you produce errors and how you report them.

You can surely achieve all of this on your own, but you will come across code that you have to maintain and test.

And one core thing to express-validator that most users don't realise: `validator` requires every value to be a string, so how you convert those when you are writing your own thing is something else to care.

**Comment by gustavohenke** [comment]
👋 this has been published to [`v6.1.0`](https://github.com/express-validator/express-validator/releases/tag/v6.1.0) 🚢

**Comment by gwh-cpnet** [comment]
I do not think the code works as documented, at least on 6.1.1

```
body('oldPassword')
  .if((value, { req }) => req.body.newPassword).not().empty().custom((value, { req }) => value !== req.body.newPassword)
```
works.

But 

```
body('oldPassword')
  .if(body('newPassword').exists())
  .not().empty()
  .custom((value, { req }) => value !== req.body.newPassword)
```

would raise Exception on `validationResult(req).throw()`.

**Comment by gustavohenke** [comment]
Hey @gwh-cpnet! What values are you testing this validator with?

**Comment by gwh-cpnet** [comment]
I think it is `Undefined`, @gustavohenke

**Comment by gwh-cpnet** [comment]
okay. Here is my `production` code that let me raise the issue.

```
api.post([
      body('driver').exists().isIn(['sqlite', 'mariadb', 'db2']),     
      body('uid').if(body('driver').isIn(['mariadb', 'db2'])).exists().trim(),
], ...);
```
above would raise exception, if driver === sqlite. but 

```
api.post([
     body('driver').exists().isIn(['sqlite', 'mariadb', 'db2']),     
     body('uid').if((value, { req }) => req.body.driver !== 'sqlite').exists().trim(),
], ...);
```

this one works as expected.

**Comment by gwh-cpnet** [comment]
@gustavohenke I have made a mocha test cases for my point. checkout it out: #762

**Pull request merged**
