### PR TITLE
Support bail in schemas

### LINKED ISSUE #848: Usage of bail() in validation schema
Hello there!
Is there a way to get similar behaviour to what bait() method does using Schema Validation? The desired behaviour is to stop validation chain after a specific validation failed (`exists` in my case)

### PR DESCRIPTION
**Pull request by tommmn**
Fix #848

### CODE REVIEW

**Comment by tommmn** [comment]
@gustavohenke  any updates on merge?

**Comment by davidmorabito** [comment]
Ship it!

**Comment by e-gloo** [comment]
Would be great to merge this PR, need it so bad.

**Comment by jeetkn4biz** [comment]
@gustavohenke What's the reason why it's not merged?

**Comment by iyiolapeter** [comment]
Can this PR be merged already?

**Comment by kkangmj** [comment]
When it'll be merged ?

**Review by fedeci — APPROVED** [review]
LGTM!
@gustavohenke what do you think?

**Comment by cforale** [comment]
hope this change will be merge

**Review by gustavohenke — APPROVED** [review]
🚀

**Comment by gustavohenke** [comment]
Published in v6.9.0!

**Pull request merged**
